# Generated by Django 4.1.4 on 2022-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("customer_secret", models.CharField(max_length=100)),
                ("resource_name", models.CharField(max_length=50)),
                ("scope", models.CharField(max_length=50)),
                ("update_date", models.DateTimeField(verbose_name="update date")),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "resource_name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("resource_secret", models.CharField(max_length=100)),
                ("update_date", models.DateTimeField(verbose_name="update date")),
            ],
        ),
    ]
