# Generated by Django 4.1.4 on 2022-12-29 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="update_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="update date",
            ),
        ),
    ]
