# Generated by Django 4.1.4 on 2022-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0002_alter_customer_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="resource_name",
            field=models.CharField(max_length=50, verbose_name="资源权限"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="scope",
            field=models.CharField(max_length=50, verbose_name="scope"),
        ),
    ]
